# .zshenv

export PATH=$HOME/bin:$PATH:/sbin:/usr/sbin

HISTFILE=$HOME/.zhist
export HISTSIZE=1000000
export SAVEHIST=1000000

export PILOTPORT=/dev/pilot

export MANSECT=1:3tcl:n:l:8:3:2:3posix:3pm:3perl:5:4:9:6:7

export DEBEMAIL=dottedmag@dottedmag.net
export DEBFULLNAME="Mikhail Gusarov"
export EMAIL="Mikhail Gusarov <dottedmag@dottedmag.net>"

if [ -e $HOME/bin/gc ]; then
    EDITOR=gc
elif [ -e /usr/bin/nano ]; then
    EDITOR=nano
fi

export EDITOR

export ACK_PAGER=less
